kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-vol
  namespace: sample-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

